version: '3.5'
services:
  traefik:
    image: traefik
    command: --web --docker --docker.watch --logLevel=DEBUG
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme
    ports:
     - 80:80
     - 443:443

  nginx:
    image: nginx
    labels:
      - traefik.backend=nginx
      - "traefik.frontend.rule=Host:findbuild.co, www.findbuild.co"
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.port=80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./dist/web:/user/share/nginx/html
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
      - proxy

  api:
    image: openjdk:12
    volumes:
      - ./dist/:/app
    ports:
      - 8080:80
    # labels:
    #   - traefik.enable=false
    # expose:
    #   - 8080
    networks:
      - internal
    environment:
      - db_server=mysql      
    command: java -jar /app/api.jar  

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    labels:
      - traefik.enable=false
    volumes:
      - ../data/mysql/datafile:/var/lib/mysql
      - ../data/mysql/mysql-files:/var/lib/mysql-files
      - ../data/mysql/datafolder:/datafolder
      # - /etc/localtime:/etc/localtime:ro
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: spdorm_db
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    external: false  