version: '3.5'
services:
  api:
    image: openjdk:12
    volumes:
      - ./dist/:/app
    ports:
     - 80:80
     - 443:443    
    networks:
      - internal
    environment:
      - db_server=mysql      
    command: java -jar /app/api.jar  

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    labels:
      - traefik.enable=false
    volumes:
      - ../data/mysql/datafile:/var/lib/mysql
      - ../data/mysql/mysql-files:/var/lib/mysql-files
      - ../data/mysql/datafolder:/datafolder
      # - /etc/localtime:/etc/localtime:ro
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: spdorm_db
    networks:
      - internal

networks:
  internal: 